global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cascade_tasks'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 5s  # Tihe채mpi ker채ys
    scrape_timeout: 4s

  - job_name: 'cascade_resources'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 30s  # Harvempi ker채ys
    scrape_timeout: 25s

  - job_name: 'cascade_alerts'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics'
    scheme: 'http'
    scrape_interval: 10s  # Keskitasoinen ker채ys
    scrape_timeout: 8s
